name: CI

on:
    pull_request: ~
    push:
        branches:
            - main
        tags:
            - '*'

jobs:
    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --no-interaction --no-suggest

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always

    nightly:
        name: PHP 8.3
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install the dependencies
              run: composer install --ignore-platform-req=php --no-interaction --no-progress

            - name: Run the unit tests
              run: vendor/bin/phpunit --colors=always
